# Generated by Django 4.2.4 on 2023-09-09 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tech_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='details',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_of_issue',
            field=models.CharField(blank=True, choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('ACCOUNT', 'Account'), ('PASSWORD', 'Password'), ('OTHER', 'Other')], default='HARDWARE', max_length=10),
        ),
    ]
