# Generated by Django 4.2.4 on 2023-09-27 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_alter_ticket_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tech_notes',
        ),
        migrations.CreateModel(
            name='TechNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_notes', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
