# Generated by Django 4.2.4 on 2023-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_remove_ticket_tech_notes_technotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technotes',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
