# Generated by Django 4.2.4 on 2023-09-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_alter_ticket_assigned_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technotes',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
