# Generated by Django 4.2.4 on 2023-09-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_technotes_created_alter_technotes_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technotes',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
